/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
    const { nodes, materials } = useGLTF("/logo.gltf");

    return (
        <group {...props} rotation={[1.5, 0, 0]} scale={1.7} dispose={null}>
            <mesh
                geometry={nodes.Border.geometry}
                material={materials.Striped}
                position={[0 - 3.5, 0.3, 0]}
            />
            <mesh
                geometry={nodes.Metris.geometry}
                material={materials.Blue}
                position={[8.19 - 3.5 - 4.96, 1.5 - 1.5, -6.13 + 3.67]}
            />
        </group>
    );
}

useGLTF.preload("/logo.gltf");
