/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
    const { nodes, materials } = useGLTF("/logo.gltf");

    return (
        <group
            {...props}
            rotation={[Math.PI / 2, 0, 0]}
            scale={18}
            dispose={null}
        >
            <mesh
                castShadow
                geometry={nodes.Border.geometry}
                material={materials.Striped}
                position={[0 - 3.5, 0.3, 0]}
            />
            <mesh
                castShadow
                geometry={nodes.Metris.geometry}
                position={[8.19 - 3.5 - 4.96, 1.5 - 1.5, -6.13 + 3.67]}
            >
                <meshToonMaterial color={0x1372d3} emissiveIntensity={0} />
            </mesh>
        </group>
    );
}

useGLTF.preload("/logo.gltf");
